CREATE TABLE students (
    student_id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    age INT,
    grade CHAR(2),
    course VARCHAR(50),
    email VARCHAR(100),
    dob DATE,
    blood_group VARCHAR(6),
    country VARCHAR(50)
)


INSERT INTO

    student (
        first_name,
        last_name,
        age,
        grade,
        course,
        email,
        dob,
        blood_group,
        country
    )
VALUES (
        'Rahim',
        'Uddin',
        20,
        'A+',
        'Computer Science',
        'rahim@example.com',
        '2005-03-15',
        'A+',
        'Bangladesh'
    ),
    (
        'Karim',
        'Hasan',
        22,
        'B',
        'Mathematics',
        'karim@example.com',
        '2003-06-25',
        'B+',
        'Bangladesh'
    ),
    (
        'Fatema',
        'Khatun',
        19,
        'A',
        'Physics',
        'fatema@example.com',
        '2006-01-10',
        'O+',
        'India'
    ),
    (
        'Jannat',
        'Ara',
        21,
        'B+',
        'Biology',
        'jannat@example.com',
        '2004-08-09',
        'AB+',
        'Bangladesh'
    ),
    (
        'Sohan',
        'Ali',
        20,
        'C',
        'Chemistry',
        'sohan@example.com',
        '2005-12-18',
        'B-',
        'Nepal'
    ),
    (
        'Mehedi',
        'Hasan',
        23,
        'A-',
        'Economics',
        'mehedi@example.com',
        '2002-04-07',
        'A-',
        'Bangladesh'
    ),
    (
        'Rina',
        'Begum',
        18,
        'B+',
        'Statistics',
        'rina@example.com',
        '2007-09-13',
        'O-',
        'Bangladesh'
    ),
    (
        'Nayeem',
        'Islam',
        20,
        'A',
        'English',
        'nayeem@example.com',
        '2005-02-19',
        'AB-',
        'Pakistan'
    ),
    (
        'Shila',
        'Akter',
        19,
        'C+',
        'Accounting',
        'shila@example.com',
        '2006-05-30',
        'A+',
        'India'
    ),
    (
        'Tariq',
        'Zaman',
        22,
        'B-',
        'Management',
        'tariq@example.com',
        '2003-11-25',
        'B+',
        'Bangladesh'
    ),
    (
        'Munira',
        'Sultana',
        20,
        'A+',
        'History',
        'munira@example.com',
        '2005-07-11',
        'O+',
        'Nepal'
    ),
    (
        'Fahim',
        'Khan',
        21,
        'B+',
        'Philosophy',
        'fahim@example.com',
        '2004-03-14',
        'A-',
        'Bangladesh'
    ),
    (
        'Laboni',
        'Nahar',
        18,
        'A',
        'Political Science',
        'laboni@example.com',
        '2007-06-22',
        'B+',
        'Bangladesh'
    ),
    (
        'Rafi',
        'Hossain',
        20,
        'C',
        'Law',
        'rafi@example.com',
        '2005-01-08',
        'O+',
        'India'
    ),
    (
        'Sadia',
        'Rahman',
        19,
        'B',
        'Sociology',
        'sadia@example.com',
        '2006-10-03',
        'AB+',
        'Bangladesh'
    ),
    (
        'Tanvir',
        'Ahmed',
        22,
        'A-',
        'Psychology',
        'tanvir@example.com',
        '2003-04-29',
        'O-',
        'Bangladesh'
    ),
    (
        'Rupa',
        'Akter',
        21,
        'C+',
        'Marketing',
        'rupa@example.com',
        '2004-12-16',
        'B-',
        'Nepal'
    ),
    (
        'Rakib',
        'Islam',
        20,
        'B+',
        'Finance',
        'rakib@example.com',
        '2005-08-20',
        'A+',
        'Pakistan'
    ),
    (
        'Nusrat',
        'Jahan',
        19,
        'A',
        'Anthropology',
        'nusrat@example.com',
        '2006-07-07',
        'AB-',
        'Bangladesh'
    ),
    (
        'Babu',
        'Mia',
        23,
        'C',
        'Environmental Science',
        'babu@example.com',
        '2002-09-01',
        'O+',
        'Bangladesh'
    );

SELECT FROM students;


